// ============================================
// Orbit — Production Pipeline Engine
// Real file operations + LLM calls + SQLite persistence
// Worker → Reviewer → Tester → Documenter → Auditor
// ============================================
import path from 'path';
import fs from 'fs/promises';
import { mkdirSync, existsSync } from 'fs';
import { v4 as uuidv4 } from 'uuid';
import { callAgent, hasRealLLM, getActiveModel } from '../server/llm';
import { executeTool, ensureWorkspace } from '../server/tools';
import {
  createPipelineRun, updatePipelineRun,
  addPipelineLog, recordWorkspaceFile,
} from '../server/db';

// ============================================
// Agent System Prompts (from agency-agents)
// ============================================

const STAGE_PROMPTS = {
  worker: `You are a Senior Software Engineer in the Orbit autonomous agent platform.
Your job is to implement the requested task completely and correctly.
Think step by step. Use tools to read existing code before writing.
Always output:
1. A summary of what you did
2. A list of files changed
3. The actual implementation
Format your response in markdown.`,

  reviewer: `You are a Staff Code Reviewer in the Orbit platform.
Review the worker's implementation for:
- Correctness and logic errors
- Security vulnerabilities
- Performance issues
- Code quality and maintainability
- Test coverage
Output your review with a clear decision: APPROVE, REVISE, or REJECT.
Be specific about issues found.`,

  tester: `You are a QA Engineer and Test Automation Specialist in the Orbit platform.
Your job is to:
1. Write comprehensive tests for the implementation
2. Run the tests using bash tool
3. Report pass/fail with detailed output
If tests fail, identify the root cause.`,

  documenter: `You are a Technical Writer in the Orbit platform.
Document the changes made:
1. Update or create README sections
2. Write API documentation
3. Add inline code comments where needed
4. Update CHANGELOG
Output the documentation in markdown.`,

  auditor: `You are a Security Auditor in the Orbit platform.
Perform a thorough security audit:
1. Check for secrets/credentials in code
2. SQL injection vulnerabilities
3. XSS vectors
4. Authentication/authorization gaps
5. Dependency vulnerabilities
Output a security report with severity ratings.`,
};

// ============================================
// Pipeline Event Types
// ============================================

export type PipelineEventType =
  | 'run:start'
  | 'stage:start'
  | 'stage:log'
  | 'stage:complete'
  | 'stage:fail'
  | 'file:created'
  | 'file:edited'
  | 'tool:call'
  | 'tool:result'
  | 'run:complete'
  | 'run:fail';

export interface PipelineEvent {
  type: PipelineEventType;
  runId: string;
  stage?: string;
  message?: string;
  data?: unknown;
  timestamp: number;
}

export type EventEmitter = (event: PipelineEvent) => void;

// ============================================
// Real Pipeline Execution
// ============================================

const PIPELINE_STAGES = ['worker', 'reviewer', 'tester', 'documenter', 'auditor'] as const;

function log(emit: EventEmitter, runId: string, stage: string, message: string) {
  addPipelineLog(runId, stage, 'info', message);
  emit({ type: 'stage:log', runId, stage, message, timestamp: Date.now() });
}

async function createWorkspaceProject(taskTitle: string, runId: string): Promise<string> {
  const ws = ensureWorkspace();
  const safe = taskTitle.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase().slice(0, 30);
  const projectDir = path.join(ws, 'projects', `${safe}-${runId.slice(0, 6)}`);
  mkdirSync(projectDir, { recursive: true });

  // Create initial project structure
  const initFiles: Record<string, string> = {
    'README.md': `# ${taskTitle}\n\nAutonomously generated by Orbit AI Platform.\n\nRun ID: \`${runId}\`\nCreated: ${new Date().toISOString()}\n`,
    'package.json': JSON.stringify({ name: safe, version: '1.0.0', description: taskTitle, private: true }, null, 2),
    'src/.gitkeep': '',
    'tests/.gitkeep': '',
  };

  for (const [file, content] of Object.entries(initFiles)) {
    const fullPath = path.join(projectDir, file);
    mkdirSync(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, content, 'utf-8');
  }

  return projectDir;
}

export async function runPipeline(
  taskTitle: string,
  taskDescription: string,
  emit: EventEmitter,
): Promise<{ runId: string; success: boolean }> {
  const runId = uuidv4();
  const startTime = Date.now();
  const model = getActiveModel();

  // Initialize DB run
  createPipelineRun({
    id: runId,
    task_title: taskTitle,
    task_description: taskDescription,
    started_at: startTime,
  });

  emit({ type: 'run:start', runId, message: taskTitle, data: { model, hasRealLLM: hasRealLLM() }, timestamp: Date.now() });
  addPipelineLog(runId, null, 'info', `Pipeline started: ${taskTitle}`);
  addPipelineLog(runId, null, 'info', `Model: ${model} | Real LLM: ${hasRealLLM()}`);

  // Create workspace project directory
  const projectDir = await createWorkspaceProject(taskTitle, runId);
  log(emit, runId, 'system', ` Workspace: orbit-workspace/projects/${path.basename(projectDir)}`);

  let workerOutput = '';
  let overallSuccess = true;
  const filesCreated: string[] = [];
  let totalInputTokens = 0;
  let totalOutputTokens = 0;

  for (const stage of PIPELINE_STAGES) {
    emit({ type: 'stage:start', runId, stage, timestamp: Date.now() });
    log(emit, runId, stage, `⟳ Starting ${stage}...`);

    try {
      // Build prompt based on stage
      let userPrompt = '';
      if (stage === 'worker') {
        userPrompt = `Task: ${taskTitle}\n\nDescription: ${taskDescription || 'Implement this task fully.'}\n\nWorkspace directory: ${projectDir}\n\nPlease implement this task completely. Create all necessary files in the workspace directory.`;
      } else if (stage === 'reviewer') {
        userPrompt = `Review the following worker output for the task "${taskTitle}":\n\n${workerOutput}\n\nProvide your review decision (APPROVE/REVISE/REJECT) with specific feedback.`;
      } else if (stage === 'tester') {
        userPrompt = `Write and run tests for the task "${taskTitle}".\n\nWorker implementation:\n${workerOutput}\n\nWorkspace: ${projectDir}\n\nCreate test files and report results.`;
      } else if (stage === 'documenter') {
        userPrompt = `Document the implementation for: "${taskTitle}"\n\nImplementation summary:\n${workerOutput}\n\nUpdate README.md in ${projectDir} with complete documentation.`;
      } else {
        userPrompt = `Perform security audit for: "${taskTitle}"\n\nImplementation:\n${workerOutput}\n\nReport all security findings with severity ratings.`;
      }

      // Call LLM (real or simulated)
      const result = await callAgent({
        systemPrompt: STAGE_PROMPTS[stage],
        userPrompt,
        stage,
        taskTitle,
        onLog: (line) => log(emit, runId, stage, line),
      });

      totalInputTokens += result.inputTokens;
      totalOutputTokens += result.outputTokens;

      log(emit, runId, stage, `  ✓ ${result.outputTokens} tokens | ${result.durationMs}ms`);

      // Worker: actually create files in workspace
      if (stage === 'worker') {
        workerOutput = result.output;

        // Create real implementation file in workspace
        const implFile = path.join(projectDir, 'src', 'implementation.md');
        await fs.writeFile(implFile, `# Implementation\n\n${result.output}`, 'utf-8');
        recordWorkspaceFile(runId, implFile, result.output, 'created');
        filesCreated.push(implFile);
        emit({ type: 'file:created', runId, stage, message: 'src/implementation.md', timestamp: Date.now() });
        log(emit, runId, stage, `   Created: src/implementation.md`);

        // Use bash tool to do real git init
        const gitResult = await executeTool(
          { id: uuidv4(), name: 'bash', args: { command: `cd "${projectDir}" && git init -q && git add -A && git commit -m "Initial commit: ${taskTitle}" --allow-empty -q 2>&1 || echo "git not available"` } },
          projectDir
        );
        log(emit, runId, stage, `   ${gitResult.output.trim().slice(0, 80)}`);
      }

      // Documenter: actually write to README
      if (stage === 'documenter') {
        const readmePath = path.join(projectDir, 'README.md');
        const readmeContent = `# ${taskTitle}

*Autonomously implemented by Orbit AI Platform*

${result.output}

---
*Generated: ${new Date().toISOString()} | Run ID: ${runId}*
`;
        await fs.writeFile(readmePath, readmeContent, 'utf-8');
        recordWorkspaceFile(runId, readmePath, readmeContent, 'updated');
        emit({ type: 'file:edited', runId, stage, message: 'README.md', timestamp: Date.now() });
        log(emit, runId, stage, `   Updated: README.md`);
      }

      // Tester: create test file
      if (stage === 'tester') {
        const testFile = path.join(projectDir, 'tests', 'implementation.test.md');
        await fs.writeFile(testFile, `# Test Results\n\n${result.output}`, 'utf-8');
        recordWorkspaceFile(runId, testFile, result.output, 'created');
        emit({ type: 'file:created', runId, stage, message: 'tests/implementation.test.md', timestamp: Date.now() });
        log(emit, runId, stage, `   Created: tests/implementation.test.md`);
      }

      // Check if reviewer rejected
      if (stage === 'reviewer') {
        const lower = result.output.toLowerCase();
        if (lower.includes('reject')) {
          log(emit, runId, stage, `  ✗ REJECTED — task needs rework`);
          overallSuccess = false;
        } else if (lower.includes('revise')) {
          log(emit, runId, stage, `   REVISE requested`);
        } else {
          log(emit, runId, stage, `   APPROVED`);
        }
      }

      emit({ type: 'stage:complete', runId, stage, data: { output: result.output, tokens: result.outputTokens }, timestamp: Date.now() });
      log(emit, runId, stage, ` ${stage} complete`);

    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log(emit, runId, stage, `  ✗ Error: ${msg}`);
      emit({ type: 'stage:fail', runId, stage, message: msg, timestamp: Date.now() });
      addPipelineLog(runId, stage, 'error', msg);
      overallSuccess = false;
      break;
    }
  }

  const duration = Date.now() - startTime;
  const costUsd = (totalInputTokens * 0.000005) + (totalOutputTokens * 0.000015);

  // Write final summary to workspace
  if (existsSync(projectDir)) {
    const summaryPath = path.join(projectDir, 'ORBIT_SUMMARY.json');
    await fs.writeFile(summaryPath, JSON.stringify({
      runId,
      taskTitle,
      taskDescription,
      success: overallSuccess,
      duration,
      filesCreated,
      inputTokens: totalInputTokens,
      outputTokens: totalOutputTokens,
      costUsd,
      model,
      completedAt: new Date().toISOString(),
    }, null, 2), 'utf-8');
  }

  // Update DB
  updatePipelineRun(runId, {
    status: overallSuccess ? 'completed' : 'failed',
    completed_at: Date.now(),
    total_duration_ms: duration,
    iterations: 1,
    cost_usd: costUsd,
    result_json: JSON.stringify({ success: overallSuccess, filesCreated }),
  });

  addPipelineLog(runId, null, 'info', `Pipeline ${overallSuccess ? 'completed' : 'failed'} in ${(duration / 1000).toFixed(1)}s | ${totalInputTokens + totalOutputTokens} tokens | $${costUsd.toFixed(4)}`);

  emit({
    type: overallSuccess ? 'run:complete' : 'run:fail',
    runId,
    data: {
      success: overallSuccess,
      duration,
      totalTokens: totalInputTokens + totalOutputTokens,
      costUsd,
      filesCreated,
      workspaceDir: path.basename(projectDir),
    },
    timestamp: Date.now(),
  });

  return { runId, success: overallSuccess };
}
